### CreatRoom
POST http://localhost:8080/auth/chat/room
Content-Type: application/json
accept: */*

{
  "roomName" : "스터티방",
  "category" : "생활영어" ,
  "memberCount" : "6",
  "lock": false,
  "roomPw" : ""
}


### ListRoom
GET http://localhost:8080/login/kakao?code=WnwNnpmmmyQ54pLnZPypPbnC72DNLnJoM7Is0Z41AYHFQowvF-4uGBPqrgvSMIw8cRQ2_QopyNkAAAGDb1WnVQ